version: '3'

volumes:
  pgdata:
  redisdata:
  localstack:

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/var/lib/redis/
  localstack-s3:
    image: localstack/localstack:0.8.7
    environment:
      - SERVICES=s3:5000
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=localstack-s3
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "5000:5000"
    volumes:
      - localstack:/tmp/localstack/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=pycon.settings.dev
      - REDIS_HOST=redis
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: celery -A pycon worker --autoreload --beat
    environment:
      - C_FORCE_ROOT=1
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=pycon.settings.dev
      - REDIS_HOST=redis
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
