
- hosts: localhost
  tasks:

  - apt_key:
      id=ACCC4CF8 url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

  - apt_repository:
      repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

  - apt: name=git-core
  - apt: name=libpq-dev
  - apt: name=make
  - apt: name=postgresql-9.3
  - apt: name=postgresql-client-9.3
  - apt: name=postgresql-server-dev-9.3
  - apt: name=python-dev
  - apt: name=python-psycopg2

  - postgresql_user: name=vagrant role_attr_flags=SUPERUSER
    become: yes
    become_user: postgres
